logging:
  level:
    org:
      hibernate:
        SQL: debug

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/eshop_baza
    username: root
    password: 'mysql'
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true